name: Storybook CI - CD

on:
  push:  
    branches: [main]
  pull_request: 
    branches: [main]


jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install --force

      - run: npm test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with: 
          name: coverage
          path: coverage/

      - uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{secrets.NPM_PUBLISH_TOKEN}}



