name: Storybook CI - CD

on:
  push:  
    branches: [main]
  pull_request: 
    branches: [main]


jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install --force

      - run: npm test

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v2
        with: 
          name: coverage
          path: coverage/

      - uses: JS-DevTools/npm-publish@v1
        with: 
          token: ${{secrets.NPM_PUBLISH_TOKEN}}


    push_to_azure_container_registry:
      runs-on: ubuntu-latest
      needs: publish
      if: ${{ success() }}

      steps:
        - uses: actions/checkout@v2

        # create the date suffix ":yyyyMMddhhmm"
        - name: Get current date
          id: date
          run: echo "::set-output name=date::$(date +'%Y%m%d%H%M')"

        - uses: azure/docker-login@v1
          with:
              login-server: ${{ secrets.ACR_SERVER }}
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}

        - run: |
              docker build . -t ${{secrets.ACR_SERVER}}/leasify/storybook:${{ steps.date.outputs.date }}
              docker tag  ${{secrets.ACR_SERVER}}/leasify/storybook:${{ steps.date.outputs.date }} ${{secrets.ACR_SERVER}}/leasify/storybook:latest 

              docker push ${{secrets.ACR_SERVER}}/leasify/storybook:${{ steps.date.outputs.date }}
              docker push ${{secrets.ACR_SERVER}}/leasify/storybook:latest



